### ISSUE TITLE
Check whether the number of trials is positive or not in `MultiStartOptimizer`

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-optimization#106]
### What is the expected enhancement?

`MultiStartOptimizer ` has a parameter `_trials` and it should be positive (> 0). Otherwise, it fails in the main loop.
We need to check it when `_trials` is set as follows. 

https://github.com/Qiskit/qiskit-optimization/blob/51628c27f70c042adf93bedbfee16eed09a53e1b/qiskit_optimization/algorithms/multistart_optimizer.py#L55
https://github.com/Qiskit/qiskit-optimization/blob/51628c27f70c042adf93bedbfee16eed09a53e1b/qiskit_optimization/algorithms/multistart_optimizer.py#L115

Discussed in https://github.com/Qiskit/qiskit-optimization/issues/41#issuecomment-825715102

**Comment by alimustafashah** [comment]
Can you assign this task to me?

**Comment by t-imamichi** [comment]
Sure. Thank you for your cooperation.
