### ISSUE TITLE
Spell check of tutorials

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-optimization#146]
Apply spell check to tutorials

**Comment by JoshDumo** [comment]
Hi! I'm new at this but I hope I can do this one. Is there a special/dedicated way to do this (scared by the Epic tag!)?

**Comment by t-imamichi** [comment]
Thank you. But, this is just an epic to manage a group of issues. They are almost done already. How about some issues with documentation tag?

**Comment by JoshDumo** [comment]
Got it,  will check those out.
