### ISSUE TITLE
Create a dockerfile for running applications benchmarks

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-optimization#179]
Our benchmarking server will run benchmarks from within a Docker container. The goal of this issue is to write a dockerfile that will create a respective Docker image with necessary dependencies which will run a bash script for benchmarking.

**Comment by t-imamichi** [comment]
Just out of curiosity. Do we need a dockerfile for each application repo? Is it sufficient to make dockerfiles in https://github.com/Qiskit/qiskit-app-benchmarks?

**Comment by dlasecki** [comment]
Benchmarks for each application repo are run by the same bash script collectively (https://github.com/Qiskit/qiskit-app-benchmarks/blob/main/tools/cron_script.sh). We need only 1 dockerfile on the server which will basically run the script above. We still need to test whether Docker provides an environment which is stable enough for benchmarking. In certain cases it might introduce unwanted spikes but there are some methods to tweak it.

**Comment by t-imamichi** [comment]
If the docker file of qiskit-opt is used for benchmarking purpose, I think it's good to make it in qiskit-app-benchmarks. Could you explain more details of the benchmarking workflow? When you take a profile, does qiskit-app-benchmarks require to clone all app repos to fetch a dockerfile for each app?

**Comment by MartinBeseda** [comment]
Dear @dlasecki ,
Dear @t-imamichi ,

can I have a look at this issue? I'd have time for that by the end of this week.

Martin

**Comment by dlasecki** [comment]
> Dear @dlasecki ,
> Dear @t-imamichi ,
> 
> can I have a look at this issue? I'd have time for that by the end of this week.
> 
> Martin

@MartinBeseda Thanks for offering help but the issue is basically done at this stage.
