### ISSUE TITLE
GraphOptimizationApplication, single responsibility principle

### ISSUE THREAD

**Issue by X-Libor** [Qiskit/qiskit-optimization#201]
### What is the expected enhancement?

the static method `random_graph` in the `GraphOptimizationApplication` 
violates the single responsibility principle. Please create some helper and move it there.

**Comment by X-Libor** [comment]
BTW, it might be ok to have some "reasonable" (not a single line application of some library) generators of random problems. For graphs I can imagine planted problems, d-regular graphs of high grith etc. I dont know if they are in some other libraries like NetworkX.

**Comment by t-imamichi** [comment]
`GraphOptimizationApplication` can take networkx graph as an input. So, we don't need to generate a random graph by `GraphOptimizationApplication`. We need to use just networkx's random graph features. Alternative is retworkx's random graphs.

**Comment by X-Libor** [comment]
Fine with me. I don't feel it should be in `GraphOptimizationApplication`. And I wanted to point out that there might be some cases that are interesting, which are not in the networkx, retworkx, and so. as I mentioned above.

**Comment by t-imamichi** [comment]
What kind of helper file do you want?
