### ISSUE TITLE
Evaluate objective function of a QuadraticProgram with a given valuation of variables.

### ISSUE THREAD

**Issue by X-Libor** [Qiskit/qiskit-optimization#212]
### What is the expected enhancement?
Add a function that evaluates the objective function of a `QuadraticProgram` with a valuation given as an input.
(Or direct me where I can find it.)

**Comment by a-matsuo** [comment]
You can find `evaluation` function here. 
https://github.com/Qiskit/qiskit-optimization/blob/cec8a3ebca5fbb309ad36d87f638f46e7d424446/qiskit_optimization/problems/quadratic_objective.py#L162
