### ISSUE TITLE
qiskit_optimization encounters an exception when trying to convert an integer variable to binary when the value of the variable is 0.

### ISSUE THREAD

**Issue by wpoxon-qci** [Qiskit/qiskit-optimization#227]
### Information

- **Qiskit Optimization version**: 0.2.1
- **Python version**: 3.8.6
- **Operating system**: AWS EC2 linux 5.4.0-1051-aws 53~18.04.1-Ubuntu SMP x86_64

### What is the current behavior?

qiskit_optimization encounters an error (`np.log2` exception) when trying to convert an integer variable to binary when the value of the integer variable is 0.

```
prob6 loaded from prob6.lp, status = QuadraticProgramStatus.VALID
/home/users/wpoxon/.pyenv/versions/3.8.6/lib/python3.8/site-packages/qiskit_optimization/converters/integer_to_binary.py:104: RuntimeWarning: divide by zero encountered in log2
  power = int(np.log2(var_range))
Traceback (most recent call last):
  File "reproducer.py", line 26, in <module>
    reproducer()
  File "reproducer.py", line 22, in reproducer
    qp_bin = int_to_bin_converter.convert(qp_eq)
  File "/home/users/wpoxon/.pyenv/versions/3.8.6/lib/python3.8/site-packages/qiskit_optimization/converters/integer_to_binary.py", line 78, in convert
    new_vars = self._convert_var(x.name, x.lowerbound, x.upperbound)
  File "/home/users/wpoxon/.pyenv/versions/3.8.6/lib/python3.8/site-packages/qiskit_optimization/converters/integer_to_binary.py", line 104, in _convert_var
    power = int(np.log2(var_range))
OverflowError: cannot convert float infinity to integer
```

### Steps to reproduce the problem

Use this input file (save it as `prob6.lp`):
```
Minimize
 obj: a + b
Subject To
 e2: a + b = 1
Bounds
 b = 0
Binaries
 a
General
 b
End
```

Then save the code below in reproducer.py and run it to reproduce the issue:

```
from qiskit_optimization.problems import QuadraticProgram
from qiskit_optimization.converters import InequalityToEquality, IntegerToBinary


def reproducer():
    lp_file = 'prob6.lp'

    qp = QuadraticProgram()
    qp.read_from_lp_file(lp_file)

    if qp.status != QuadraticProgram.Status.VALID:
        print(f'{lp_file} failed to load.')
        return

    print(f'{qp.name} loaded from {lp_file}, status = {qp.status}')

    ineq_to_eq_converter = InequalityToEquality()
    qp_eq = ineq_to_eq_converter.convert(qp)

    int_to_bin_converter = IntegerToBinary()
    qp_bin = int_to_bin_converter.convert(qp_eq)


if __name__ == '__main__':
    reproducer()


```

### What is the expected behavior?

integer variables with a zero value in an LP-format input file should not cause the integer-to-binary converter to encounter an exception.

### Suggested solutions

The relevant code in `qiskit_optimization/converters/integer_to_binary.py` is in class `IntegerToBinary` in the `_convert_var()` function.

If this code is called with an integer variable that has a zero value (which leads to `var_range` having a zero value), an exception is raised on this line:

`power = int(np.log2(var_range))`

when `np.log2()` is called when `var_range` is 0.

**Comment by t-imamichi** [comment]
If the variable range is zero, it is good to substitute the variable with the corresponding constant value using `QuadraticProgram.substitute`. Maybe we need to tweak int2bin converter to do it or somewhere else.

**Comment by wpoxon-qci** [comment]
Thank you very much for investigating this issue and for your very quick response!

I will follow up with a question / suggestion in #228.

**Comment by wpoxon-qci** [comment]
@t-imamichi - I just wanted to check with you again and see if there are any plans yet for a new release which would include the fix for this issue. Thank you!

**Comment by t-imamichi** [comment]
Hi. We released a new version with this fix today.
