### ISSUE TITLE
Add or tweak a converter to deal with trivial variables and constraints

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-optimization#228]
### What is the expected enhancement?

`QuadraticProgram` may include trivial variables and constraints.
For example, #227 includes a trivial variable (lower bound and upper bound are equal).

Here is an example of a trivial constraint.
```python
from qiskit_optimization.problems import QuadraticProgram

qp = QuadraticProgram()
qp.linear_constraint(sense='==', rhs=1)  # constraint: 0 == 1
```
It is good to eliminate such trivial cases in some existing converters or a new converter.

Fixes #227

**Comment by atulanand206** [comment]
Hi @t-imamichi 

I'd like to fix this problem. 

I went through the piece of code mentioned #227 and we have to find a workaround when the bounds range is 0. We could set the value of power as 0 directly which calculating the `np.log2(var_range)`. This would prevent the exception from being raised.

I've little to no idea about the purpose of the converters but just isolating the method seems solvable. I've a mathematical background, so understanding equations won't be a problem.

What is the recommendation?

**Comment by t-imamichi** [comment]
Thank you for raising a hand for this issue.
Because it is more important to fix the bug #227, I recommend to add a workaround for `IntegerToBinary` converter.
As I commented https://github.com/Qiskit/qiskit-optimization/issues/227#issuecomment-900953877, if variable range is zero, we can substitute the variable with a constant value.

Estimated tasks are as follows:
- Apply `QuadraticProgram.substitute` in `IntegerToBinary` when variable range is zero
- Add unit tests in https://github.com/Qiskit/qiskit-optimization/blob/main/test/converters/test_converters.py
- Add a [release note](https://github.com/Qiskit/qiskit-optimization/blob/main/CONTRIBUTING.md#release-notes)

**Comment by wpoxon-qci** [comment]
I have one quick question / suggestion:

Would a potential fix be to insert a check here (above this line):
https://github.com/Qiskit/qiskit-optimization/blob/103db34daf68f0d4c93a558891a50bb0b5de2450/qiskit_optimization/converters/integer_to_binary.py#L104

for `if var_range:`

and only execute the rest of the current code in `_convert_var()` if `var_range` is non-zero?

Then it might work to add:
```
    else:
        # add some code to create one or more binary variables as needed to hold the value of `lowerbound`
```

I am not sure - it's just a suggestion I had after reviewing the current code.

Thank you again for your quick response and for investigating this issue and working on a fix!

**Comment by t-imamichi** [comment]
@wpoxon-qci Thank you for your solution. It looks good to be a workaround. Just I suggest `power = int(np.log2(var_range)) if var_range > 0 else 0` to be clear.
As I wrote https://github.com/Qiskit/qiskit-optimization/issues/228#issuecomment-901268665, it's OK to make a PR with a workaround, unit tests, and a release note.

**Comment by t-imamichi** [comment]
@wpoxon-qci I made another bug fix of int2bin #230. If you are OK, I can include your suggestion as part of #230. If you want to make your own PR, it's also alright. What do you think?

**Comment by wpoxon-qci** [comment]
> @wpoxon-qci Thank you for your solution. It looks good to be a workaround. Just I suggest `power = int(np.log2(var_range)) if var_range > 0 else 0` to be simple (1 line) and clear (">0" part).

@t-imamichi - Thank you for your improvements to my proposed fix.  I like your version of the change better.  I can take your proposed change and run it in my environment and provide confirmation that it fixes my original issue in #227.  It should be fine, but I will just try it and provide positive confirmation.

**Comment by wpoxon-qci** [comment]
> @wpoxon-qci I made another bug fix of int2bin #230. If you are OK, I can include your suggestion as part of #230. If you want to make your own PR, it's also alright. What do you think?

@t-imamichi - if you are already working on a PR for another fix in the int2bin code, please go ahead and include the fix for this issue in your other PR.  Thank you!

**Comment by wpoxon-qci** [comment]
@t-imamichi - just confirming.  Your suggested version of the fix also works to resolve the original issue I submitted in #227.
I re-ran my test and it passed with the modifications to the fix that you suggested.  Here is an updated version of the change that I tested with:

```
@@ -101,7 +107,7 @@
         self, name: str, lowerbound: float, upperbound: float
     ) -> List[Tuple[str, int]]:
         var_range = upperbound - lowerbound
-        power = int(np.log2(var_range))
+        power = int(np.log2(var_range)) if var_range > 0 else 0
         bounded_coef = var_range - (2 ** power - 1)
 
         coeffs = [2 ** i for i in range(power)] + [bounded_coef]

```
If you are willing to include this change when you make your other int2bin fix in #230 that would be excellent.  Thank you!

**Comment by atulanand206** [comment]
@wpoxon-qci I was thinking exactly the same. Apologies it took me a while to revert.

As @t-imamichi is already working on this, he can proceed and add it in his PR. If required, I can raise a fix for this post confirmation.

I'd happy to look at any other outstanding issue. Would be glad if you can point in the relevant direction.

**Comment by t-imamichi** [comment]
Thank you, @wpoxon-qci. I will include @wpoxon-qci's solution in #230.

@atulanand206 We still need to handle trivial variables and constraints even if we merge #230. If you wish, you can work on it. I will add another issue for the topic because we discussed a lot about the workaround in this thread already. I would like to avoid confusion of discussion.
