### ISSUE TITLE
Request: extend the options and the information returned by MinimumEigenOptimizer.solve

### ISSUE THREAD

**Issue by EliasCombarro** [Qiskit/qiskit-optimization#256]
If I understood the code correctly, currently MinimumEigenOptimizer.solve returns the "best" solution of those with sampling probability at least 1e-6. In my opinion, this is a little bit confusing (at least, it had me scratching my head for a couple of hours) because no information of the actual probability of finding that solution is given. I was comparing the results obtained by using QAOA directly and MinimumEigenOptimizer(QAOA) and I had a really hard time understanding why MinimumEigenOptimizer was able to obtain the minimum energy solution while QAOA was only giving a probability of about 1e-3 to it. Only after reading the code did I understand what was going on. 

I suggest adding options to the "solve" method so you can, for instance, select only solutions with probability above a given threshold, obtain a list of solutions ordered by probability, obtain only the most likely solution or something along those lines. Additionally, information on the probability of each solution returned could be added. 

Thanks in advance.

**Comment by t-imamichi** [comment]
Thank you for your feedback. The threshold `min_probability` is not documented in the public classes or methods and users cannot change the value either. Removing `min_probability` would be an option.

**Comment by EliasCombarro** [comment]
Thanks. I am not sure how the min_probability removal you propose would work. Would all the solutions be considered regardless of their probability? In that case, the correct solution would be returned every time, wouldn't it?

Thanks in advance!

Elías

**Comment by t-imamichi** [comment]
As for the filter of solutions, pick up the most likely solution, or sort of solutions with different criteria, you can do it by analyzing the solution samples. See [a tutorial](https://qiskit.org/documentation/optimization/tutorials/03_minimum_eigen_optimizer.html#Analysis-of-Samples).
It might be better for us to mention in tutorials and/or API references that `OptimizationResult.{x, fval}` is the best solution among all samples.

**Comment by EliasCombarro** [comment]
Thanks, I, had somehow missed that tutorial. It is really heplful.

**Comment by t-imamichi** [comment]
You are welcome. Then, I close this issue.

**Comment by EliasCombarro** [comment]
Yes, thanks. Although I still think that it would be good to mention that "solve" returns the best solution irregardlessly of its probability
