### ISSUE TITLE
Question: optimization of a problem with continuous variable

### ISSUE THREAD

**Issue by gcattan** [Qiskit/qiskit-optimization#283]
Hello, 

I would like to conduct some optimization of a model containing matrices with continuous variables. 
Is rounding to some precision and converting integers to binaries a correct way to do this?
Can I expect an outcome (in terms of precision) as compared to a "classical" computation?

Thank you in advance for the help or any resource you might point me to.

**Comment by t-imamichi** [comment]
ADMM might be applicable to deal with your model with continuous variables. See https://qiskit.org/documentation/optimization/tutorials/05_admm_optimizer.html

**Comment by gcattan** [comment]
Thank you very much for this useful resource. What I understand after reading the doc is that continuous variables will be optimized with a classical solver, and only unconstraint binary variables will be optimized on quantum.

Is there a way to convert continuous variables in such a way they can be quantumly optimized (with some advantage)?
Or is there a plan to implement a similar feature in a near future?

**Comment by t-imamichi** [comment]
If you want to deal with continuous variables quantumly, you need to encode it with qubits. Because the number of qubits is very limited, you need to encode it by yourself, for example, in a form `coeff * integer_var`.

**Comment by gcattan** [comment]
Ok, thank you for the answer. Do you know if there is a plan to implement something like QAOA for continuous problems in the future?

**Comment by t-imamichi** [comment]
I don't think we have any plan for that direction. We welcome your idea to realize it.

**Comment by gcattan** [comment]
Ok, thank you for your time.
