### ISSUE TITLE
CI should run unit tests with and without cplex

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-optimization#29]
As the majority of codebase here is designed to work without the optional `cplex` package being installed we should run tests in such an environment to ensure this works as expected without cplex. The docplex package has linkage to cplex and some functions depend on cplex - by testing without cplex we continue to ensure that things operate as expected whether its the logic here and/or docplex that might change over time. Perhaps this test just needs to be done on the more popular Python version(s) - we want to avoid increasing too much the duration of the unit test run.

**Comment by adekusar-drl** [comment]
Please include CVXPY also.
