### ISSUE TITLE
LinearEqualityToPenalty.penalty doesn't return the penalty factor used in conversion

### ISSUE THREAD

**Issue by peguerosdc** [Qiskit/qiskit-optimization#34]
### Information

- **Qiskit Optimization version**: latest
- **Python version**: 3.8.5
- **Operating system**: Ubuntu 20.04.2 LTS

### What is the current behavior?
After creating a converter `LinearEqualityToPenalty` with no penalty factor and converting a `QuadraticProgram`, calling `.penalty` doesn't return the penalty factor used in conversion as stated in the docs.

### Steps to reproduce the problem
```` python
# Create a quadratic program
qp = QuadraticProgram()
# After adding your constraints, convert the inequality constraints to penalties with LinearEqualityToPenalty
converter = LinearEqualityToPenalty()
converted_qp = converter.convert(qp)
# Calling .penalty returns None
converter.penalty
````

### What is the expected behavior?
Docs say that calling `.penalty` "returns the penalty factor used in conversion" and that is the expected result, but instead it returns `None` when no default penalty is set.

### Suggested solutions
Checking the code, when no penalty is provided in the constructor and `convert` is called, a penalty factor is calculated using `LinearEqualityToPenalty._auto_define_penalty()`, but `self._penalty` is not updated.

I can fix it as it would be just adding a single line after calculating the penalty in `convert` like this:

````python
if self._penalty is None:
    penalty = self._auto_define_penalty()
    self._penalty = penalty
else:
    penalty = self._penalty
````
(and maybe it's not much, but it would be my first Qiskit contribution ever 🎉), or if it is coded like this for a reason, I think the docs should be updated as they are a little misleading (I can do it as well if the rationale behind that decision is explained to me 🙂 )

**Comment by a-matsuo** [comment]
Hi @peguerosdc 
thank you for the issue! Currently, `self._penalty` is used as a flag for whether the converter calls `self._auto_define_penalty()` or not. If we update `self._penalty` and fix it, `self._auto_define_penalty()` will not be called when people reuse the converter. How about adding a new variable something like `auto_define_penalty` variable, and we use it for the flag of `self._auto_define_penalty()` and update `self._penalty`? In this way, we can correctly reuse the converter. It might be a little bit difficult task for the first contribute. Can you do this?
