### ISSUE TITLE
tutorial typo

### ISSUE THREAD

**Issue by poig** [Qiskit/qiskit-optimization#379]
### may be a typo
docs/tutorials/07_examples_vehicle_routing.ipynb:94
``Following [5], the algorithm can be summarized as follows:``
### comment
``[5]`` might be also a reference but only four references provided

**Comment by t-imamichi** [comment]
Thank you for the report. I think `[5]` should be `[2]`. Do you perhaps have any idea, @adekusar-drl?

> [1] E. Farhi, J. Goldstone, S. Gutmann e-print arXiv 1411.4028, 2014
> [2] [Max-Cut and Traveling Salesman Problem](https://qiskit.org/documentation/optimization/tutorials/06_examples_max_cut_and_tsp.html)
> [3] C. E. Miller, E. W. Tucker, and R. A. Zemlin (1960). “Integer Programming Formulations and Travelling Salesman Problems”. J. ACM. 7: 326–329. doi:10.1145/321043.321046.
> [4] D. L. Applegate, R. M. Bixby, V. Chvátal, and W. J. Cook (2006). The Traveling Salesman Problem. Princeton University Press, ISBN 978-0-691-12993-8.

**Comment by adekusar-drl** [comment]
Oh, that was some time ago. In the original version [5] is missing as well. I'd suggest to remove this reference and keep only "The algorithm can be summarized as follows" as I just don't recall what [5] could be.

**Comment by t-imamichi** [comment]
Thanks. I update the note following your suggestion in #448.
