### ISSUE TITLE
The function get_vehiclerouting_solution fails with qasm_simulator

### ISSUE THREAD

**Issue by AzizNgoueya** [Qiskit/qiskit-optimization#39]
### Information

- **Qiskit Aqua version**: 0.8.1
- **Python version**:  3.9.1
- **Operating system**: Windows

### What is the current behavior?
The method get_vehiclerouting_solution from the optimization module produces a keyerror when trying to solve a vehicle routing on Aer qasm_simulator. This works on Aer statevector_simulator.

### Steps to reproduce the problem
running the vqe algorithm for this problem and using the following method
`get_vehiclerouting_solution(instance, n, K, result_vqe)` 

### What is the expected behavior?
This should work with qasm_simulator

### Suggested solutions
I think that the eigenstate format of the vqe result(a dict for qasm_simulator)  is not taken into account in this function.

**Comment by woodsp-ibm** [comment]
This is more than 2 years old, was originally raised in Aqua, things have changed a lot since then, the way things are done now are very different and the function no longer even exists. So closing as stale.
