### ISSUE TITLE
Special patterns of inequality to penalty converters

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-optimization#40]
### What is the expected enhancement?

When users solve an optimization problem with Qiskit Aqua, they apply `InequalityToEquality` to convert inequality constraints into equality constraints by introducing slack variables, and then apply `LinearEqualityToPenalty` to translate the constraints into penalties of the objective function of QUBO. But, there are some special patterns are known that does not require slack variables. The objective of this issue is to implement such special converters.

[A Tutorial on Formulating and Using QUBO Models](https://arxiv.org/abs/1811.11538) introduces examples of the special patterns in page 10 as follows.
![image](https://user-images.githubusercontent.com/31178928/92363149-08fee900-f12c-11ea-9ca7-74b1a4b5f26d.png)

**Comment by a-matsuo** [comment]
My mentees are working on this issue for their qiskit advocate mentorship program. They will finish implementing by the end of May.

**Comment by t-imamichi** [comment]
Thanks. It would be better to share the WIP PR as a draft PR here. It is easier for us to comment it.

**Comment by t-imamichi** [comment]
Could you link to the mentoring issue to this issue and the upcoming PR?

**Comment by a-matsuo** [comment]
Sure [qiskit-advocate-mentorship-program#24](https://github.com/qiskit-community/qiskit-advocate-mentorship-program/issues/24). I will link a PR once we create it.
