### ISSUE TITLE
ValueError: 'to_matrix' will return an exponentially large matrix

### ISSUE THREAD

**Issue by gcattan** [Qiskit/qiskit-optimization#401]
### Environment

- **Qiskit Optimization version**: 0.4.0
- **Python version**: 3.8
- **Operating system**:  Windows 10

### What is happening?

I guess it is more a question than a real issue.

I have an optimization problem, with 5 variables.
Each variable is a matrix of size 2x2 containing integer variables.
I am using `IntegerToBinary` to convert the problem, as below:

```
def _solve_qp(self, qp):
        conv = IntegerToBinary()
        qubo = conv.convert(qp)
        backend = BasicAer.get_backend('statevector_simulator')
        quantum_instance = QuantumInstance(backend)
        qaoa_mes = QAOA(quantum_instance=quantum_instance,
                        initial_point=[0., 0.])
        qaoa = MinimumEigenOptimizer(qaoa_mes)
        return conv.interpret(qaoa.solve(qubo))
```

When I run the code above, I am getting this error:
```
 ValueError: 'to_matrix' will return an exponentially large matrix, in this case '7588550360256754183279148073529370729071901715047420004889892225542594864082845696x7588550360256754183279148073529370729071901715047420004889892225542594864082845696' elements. Set algorithm_globals.massive=True or the method argument massive=True if you want to proceed.
```

I am not sure whether my reasoning is wrong or if this is a limitation of Qiskit.
Could you help me, please?

### How can we reproduce the issue?

N/A

### What should happen?

N/A

**Comment by t-imamichi** [comment]
Could you paste the entire script to [gist](http://gist.github.com/) to reproduce the error?

**Comment by gcattan** [comment]
Sure. Please find the gist [here](https://gist.github.com/gcattan/176ed5891deeb62dc3b21c686bf37167).

**Comment by gcattan** [comment]
@t-imamichi were you able to reproduce the error with the gist?

**Comment by t-imamichi** [comment]
Because you use unbound integer variables (no lower bound and no upper bound), they are converted into a large set of binary variables to generate a qubo. I printed out your problem and the result is as follows. The number of variables (272) is too much, which corresponds to the number of qubits.

```
input problem Problem name: docplex_model1

Minimize
  5*fro_mean_0_0^2 + 5*fro_mean_0_1^2 + 5*fro_mean_1_0^2 + 5*fro_mean_1_1^2

Subject to
  No constraints

  Integer variables (4)
    fro_mean_0_0   # no lower bound and no upper bound displayed.
    fro_mean_0_1
    fro_mean_1_0
    fro_mean_1_1

num variables of qubo: 272
```

**Comment by gcattan** [comment]
Ok, I understand, thank you for your answer.
