### ISSUE TITLE
TSPLIB parser

### ISSUE THREAD

**Issue by MinssenP** [Qiskit/qiskit-optimization#408]
### Environment

- **Qiskit Optimization version**: 0.4.0
- **Python version**: 3.9
- **Operating system**: Mac OS

### What is happening?

The TSPLIB parser in TSP application do not parse TSPLIB files from http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/index.html. 

### How can we reproduce the issue?

Download a tsp instance [st70](http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/tsp/st70.tsp.gz) and extract st70.tsp

``` 
from qiskit_optimization.applications.tsp import Tsp

read_path = "st70.tsp"
tsp = Tsp.parse_tsplib_format(read_path)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/py39/lib/python3.9/site-packages/qiskit_optimization/applications/tsp.py", line 165, in parse_tsplib_format
    raise QiskitOptimizationError(
qiskit_optimization.exceptions.QiskitOptimizationError: 'This supports only "TSP" type. Actual:  TSP\n'
```

### What should happen?

Should parse the file and create the TSP object.

### Any suggestions?

strip() is not an inplace method [line 163](https://github.com/Qiskit/qiskit-optimization/blob/main/qiskit_optimization/applications/tsp.py#L163) thus the bug line 165. Simple fixes like this would suffice 
```
name = name.strip()
typ = typ.strip()
```
Then TSPLIB may have End Of File entry like in st70.tsp, see [TSPLIB documentation](http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/tsp95.pdf). Adding an extra condition is sufficient.
```
elif line.startswith("EOF"):
    continue
```
Happy to be assigned on this issue.

**Comment by t-imamichi** [comment]
Thank you for pointing out this issue. If you are happy to contribute to qiskit optimization, feel free to work on it.
