### ISSUE TITLE
Support new primitive based algorithms.

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-optimization#425]
### What is the expected enhancement?

Support primitive based algorithms such as the new QAOA and SamplingVQE etc accordingly.

Update GroverOptimizer to move away from QuantumInstance use, potentially by more directly using Grover from Terra.

Update tutorials correspondingly

Update readme sample

Migration guide as applicable

- [x] MinimumEigenOptimizer (@t-imamichi) #436
- [x] GroverOptimizer (@a-matsuo) #437
- [x] documentation #436
- [x] migration guide / tutorials #448

**Comment by t-imamichi** [comment]
Tutorials and migration guide have just been merged #448. So, I think we can close this issue.

**Comment by woodsp-ibm** [comment]
> So, I think we can close this issue.

Yes. I think so.

Maybe though, if you note above I mentioned for the GroverOptimzer the direct use of Grover algorithm from Terra. When the GroverOptimzer was originally done the Grover at that time was not as flexible. But now its likely that the Grover algorithm can be used here rather than the custom logic/circuits here. There was no time to look into this though for the current release but it may be worth raising a separate issue to cover this so it can be looked at later.

**Comment by t-imamichi** [comment]
Thank you for reminding me of `GroverOptimizer`. Is this https://github.com/Qiskit/qiskit-optimization/pull/437/files#r1024573314 the discussion?

**Comment by woodsp-ibm** [comment]
That certainly was the most recent discussion, yes. The idea has been floating around for a while though.
