### ISSUE TITLE
`tsp.interpret` returns nested lists

### ISSUE THREAD

**Issue by rpitasky** [Qiskit/qiskit-optimization#426]
The return type of `tsp.interpret` seems quite strange: https://github.com/Qiskit/qiskit-optimization/blob/3276eaa9917e03923a76390050ed5cea2ecae6e6/qiskit_optimization/applications/tsp.py#L65

Sometimes when running tsp.interpret on a valid result, one can get complete nonsense like `[4, [2, 3], [], 1]`. In a project of mine, I solved this with `np.hstack` (see [my code here](https://github.com/rpitasky/qiskit-gcode-path-optimization/blob/d086257f18ef63509e64099ddfa59a0fe13d7eec/main.py#L150)) but it's strange to me that this is a problem at all.

I would expect a simple one-dimensional array of indices, and the tutorial does too! See https://github.com/Qiskit/qiskit-optimization/blob/3276eaa9917e03923a76390050ed5cea2ecae6e6/docs/tutorials/06_examples_max_cut_and_tsp.ipynb?short_path=a29aa13#L852.

After a little bit of poking around in the code, it seems to me like the iteration in the `tsp.interpret` function is handled wrong.

I would not mind fixing this if I get confirmation that this is an actual issue and not me misinterpreting something :)

**Comment by rpitasky** [comment]
This issue runs deeper than I thought. Looking through old commits, it seems like there was a note about how the output can contain nested lists if the result is infeasible, but this was removed when the whole applications module was refactored in #31  https://github.com/Qiskit/qiskit-optimization/blob/c14e2603b29ded8847d57288831c5ee0563dd5c4/qiskit_optimization/applications/ising/tsp.py#L257-L261

I'm still getting weird results even when the result is considered feasible; consider this run I produced:
```
feasible: True
solution: [3, [], 1, 2]
```

<details>
<summary>Parameters I used to generate this error</summary>
This is just a sketch of the code.

```python3
tsp = Tsp.create_random_instance(nodes, seed=333337)
algorithm_globals.random_seed = 123
seed = 10598

qp = tsp.to_quadratic_program()
qp2qubo = QuadraticProgramToQubo()
qubo = qp2qubo.convert(qp)
qubitOp, offset = qubo.to_ising()

quantum_instance = QuantumInstance(Aer.get_backend("qasm_simulator"), seed_simulator=seed, seed_transpiler=seed)
spsa = SPSA(maxiter=300)
ry = TwoLocal(qubitOp.num_qubits, "ry", "cz", reps=10, entanglement="linear")
vqe = VQE(ry, optimizer=spsa, quantum_instance=quantum_instance)

result = vqe.compute_minimum_eigenvalue(qubitOp)

x = tsp.sample_most_likely(result.eigenstate)
print("feasible:", qubo.is_feasible(x))
z = tsp.interpret(x)
print("solution:", z)

# x is [0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0]
```
</details>

I'm still looking for the source of the discrepancy (interestingly, using `NumPyMinimumEigensolver` does not have this issue at all).

**Comment by t-imamichi** [comment]
Could you take a look at it, @a-matsuo?

**Comment by a-matsuo** [comment]
Sure, I look into it.

**Comment by a-matsuo** [comment]
The behavior is expected, isn't it? Since `qubo` does not have constraints, it will return `feasible` for any solution. If you use `qp.is_feasible(x)` instead of `qubo.is_feasible(x)`, it will return `False`.

**Comment by rpitasky** [comment]
Why is `qp.is_feasible(x)` false here, given that this is a valid, solvable TSP problem? Is this indicative of a problem somewhere in the TSP -> QP chain of conversions?

**Comment by a-matsuo** [comment]
I mean `x=[0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0]` as you showed in the above is an invalid solution, isn't it? It never visits `city 0`. `is_feasible(x)` checks whether a given `x` violates constraints or not.

**Comment by t-imamichi** [comment]
VQE does not guarantee the optimality and the solution does not always satisfy all constraints. So, although `qubo.is_feasible(x) == True` of the solution `x=[0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0]` (QUBO has no constraint), `qp.is_feasible(x) == False`. If `qp.is_feasible(x) == False`, `interpret` may generate a nonsense list due to the infeasibility.

**Comment by rpitasky** [comment]
Makes sense, thank you for your help.
