### ISSUE TITLE
Get circuit using QAOA function

### ISSUE THREAD

**Issue by shadibeh** [Qiskit/qiskit-optimization#468]
### What should we add?

Hi everyone.

I am using the following code 
`algorithm_globals.random_seed = 12345
quantum_instance = QuantumInstance(
    BasicAer.get_backend("statevector_simulator"),
    seed_simulator=algorithm_globals.random_seed,
    seed_transpiler=algorithm_globals.random_seed,
)
qaoa_mes = QAOA(quantum_instance=quantum_instance, initial_point=[0.0, 1.0])
qaoa = MinimumEigenOptimizer(qaoa_mes)`

I need to get the circuit that is constructed by this code. 
Would you please how I can get the circuit?
Thanks

**Comment by t-imamichi** [comment]
You can get the circuit by `qaoa_mes.min_eigen_solver.ansatz`.
