### ISSUE TITLE
Initialization of optimizer

### ISSUE THREAD

**Issue by shadibeh** [Qiskit/qiskit-optimization#469]
### What should we add?

Hi every one. 

I was wondering if it is possible to initialize optimizer. I mean the optimizer always start with specified initial value of parameter.

Thanks

**Comment by woodsp-ibm** [comment]
Do you mean the classical `optimizer`, such as `SLSQP`, `SPSA` etc that is used with `QAOA`? The answer is that you can, its done using `initial_point` - see this https://qiskit.org/documentation/optimization/tutorials/03_minimum_eigen_optimizer.html#Solving-a-QUBO-with-the-MinimumEigenOptimizer for an example.

**Comment by shadibeh** [comment]
Thanks for the reply.
The code that I am running follows as:

`from skopt import Optimizer
import tqdm
eps = 1e-6
bounds = (
    [(0.0        + eps, qu.pi / 2 - eps)] * p + 
    [(-qu.pi / 4 + eps, qu.pi / 4 - eps)] * p
)

bopt = Optimizer(bounds)
import tqdm
for i in tqdm.trange(100):
    x = bopt.ask()
    res = bopt.tell(x, energy(x), initial_point=x0)
`

That is the error that I get:
TypeError: tell() got an unexpected keyword argument 'initial_point'
