### ISSUE TITLE
Make matplotlib extra_required

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-optimization#55]
### What is the expected enhancement?

As Steve and I discussed in #51, we need to discuss whether matplotlib is required or extra_required.
`GraphOptimizationApplication.draw` depends on `networkx.draw` and `networkx.draw` depends on matplotlib.
`VehicleRouting` also depends on `matplotlib`.

The application classes need to check whether matplotlib is installed or not and raise `MissingOptionalLibraryError` if not installed.

But, users who don't visualize graph results don't need matplotlib. So, it is reasonable to make matplotlib extra_required as same as `qiskit[visualization]`. In this case, we need to detect whether matplotlib is installed or not in the application classes to show some messages if `draw` is called but matplotlib is not installed.

matplotlib is not included setup.py and requiements.txt (it is included in requirements-dev.txt). So, default users cannot use `draw` currently.

**Comment by woodsp-ibm** [comment]
As I mentioned in #51 to me its odd (read not really correct) to include a dependent of a dependent. Clearly networkx, if you just install that, its draw() does not work unless MatPlotLib is installed. It does not install it by default either and has it has extra_requires itself. If you do call draw() then, as you showed in #55, the error about not having MatPlotLib is spelled out. So to me detecting it and raising a similar error seems unneeded. At a minimum though I agree this should be documented, and as I said I am not totally averse to having some extra_requires if its thought it would help.

**Comment by woodsp-ibm** [comment]
@stefan-woerner @manoelmarques in case you wish to jump in at all on this...
