### ISSUE TITLE
Add textual representations to optimization objects

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-optimization#77]
### What is the expected enhancement?
Many optimization objects, e.g. `Constraint`, `Variable` do not have textual representations, e.g. methods like `__str__` and `__repr__` and in a debugger, e.g. PyCharm they don't provide much information out of box. `QuadraticProgram` has only `__repr__` which, in turns, depends on the docplex implementation, and in the debugger you can only see a docplex comment header of the LP representation.

This issue should be fixed by reviewing optimization objects and introducing textual representation methods in them.

**Comment by t-imamichi** [comment]
The current `__repr__` does not follow the Python's convention. We should fix it.

> `object.__repr__(self)`
> Called by the repr() built-in function to compute the “official” string representation of an object. If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment). If this is not possible, a string of the form <...some useful description...> should be returned.
https://docs.python.org/3/reference/datamodel.html#object.__repr__

> `object.__str__(self)`
> Called by str(object) and the built-in functions format() and print() to compute the “informal” or nicely printable string representation of an object. The return value must be a string object.
https://docs.python.org/3/reference/datamodel.html#object.__str__
