### ISSUE TITLE
Add visualization of solution samples

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-optimization#81]
### What is the expected behavior?

Optimization results include not only the best solution but also the solution samples.
It would be nice to visualize the distribution of the solutions such as a histogram like [plot_histogram](https://qiskit.org/documentation/tutorials/circuits/2_plotting_data_in_qiskit.html#Plot-histogram).

![image](https://user-images.githubusercontent.com/31178928/114679569-3c02fe00-9d47-11eb-8000-c65961c1e546.png)

**Comment by pawmasz** [comment]
@t-imamichi can I take a look at this?

**Comment by t-imamichi** [comment]
Sure. Feel free to work on it.

**Comment by MartinBeseda** [comment]
@pawmasz @t-imamichi Is this issue still being worked on? If it isn't I'd take a look at it - if it is, I'm sorry to bother your both.

Martin

**Comment by pawmasz** [comment]
Go ahead 😉

**Comment by t-imamichi** [comment]
I think the examples in #152 are enough for most users to visualize the samples.
