### ISSUE TITLE
Add a tutorial to describe how to use samples of the optimization result

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-optimization#82]
### What is the expected enhancement?

The optimization result includes not only the best solution but also solution samples.
It would be nice to write a tutorial to introduce how to use samples, e.g., compute statistics such as mean, percentile, standard deviation and visualize a histogram #81.

**Comment by MartinBeseda** [comment]
Dear @t-imamichi , I'd have a look at this one. Just one beginner question - is the samples' structure same for all the optimization methods as listed [here](https://qiskit.org/documentation/tutorials/optimization/index.html)? Thank you very much for the answer,
Martin

**Comment by t-imamichi** [comment]
Hi, thank you for having an interest in this task. The original tutorials are in this directory. https://github.com/Qiskit/qiskit-optimization/tree/main/docs/tutorials

**Comment by MartinBeseda** [comment]
Dear @t-imamichi , I've opened a pull request with the supplemented documentation (10_warm_start_qaoa.ipynb, section Analysis), where I've added info about usage of samples.

I've also written few simple functions to demonstrate the usage:

```
def get_filtered_samples(samples: List[SolutionSample],
                         percentile: float = 0,
                         allowed_status: Tuple[OptimizationResultStatus] = (OptimizationResultStatus.SUCCESS,)):
    res = []
    for s in samples:
        if s.status in allowed_status and s.probability > percentile:
            res.append(s)

    return res


def print_samples(samples: List[SolutionSample],
                  max_len: int = None):
    return ['{}: fval: {:.4f}, probability: {:.2f}'.format(e.x, e.fval, e.probability)
            for e in sorted(samples, key=lambda x: x.probability, reverse=True)][:max_len]


class PropertyChoice(Enum):
    FVAL = 0
    PROBABILITY = 1


def get_samples_mean(samples: List[SolutionSample],
                     property: PropertyChoice = PropertyChoice.FVAL):
    return np.mean([(e.fval if property is PropertyChoice.FVAL else e.probability) for e in samples])


def get_samples_std(samples: List[SolutionSample],
                    property: PropertyChoice = PropertyChoice.FVAL):
    return np.std([(e.fval if property is PropertyChoice.FVAL else e.probability) for e in samples])


def get_samples_property(samples: List[SolutionSample],
                         property: PropertyChoice = PropertyChoice.PROBABILITY):
    return {''.join(str(int(_)) for _ in s.x): (s.fval if property is PropertyChoice.FVAL else s.probability)
            for s in samples}
```

Would it be useful to include them in some form as methods into `OptimizationResult` object?

Also, I didn't use code provided in #82, as the pull request isn't accepted yet.

And finally, thank you for all your input and recommendations about the possible improvements!

**Comment by t-imamichi** [comment]
First of all, I appreciate your contributions. As I commented at #152, you section might be good to move 03_minimum_eigen_optimizer because it is more general optimizer. On the other hand, warm start QAOA is a special type of optimizer.

As for your utility functions, I don't think we need to include it as part of `OptimizationResult` because they are mostly one line and users can easily write a similar stuff. But, I would like to discuss it if more other users want them as part of `OptimizationResult`.

**Comment by MartinBeseda** [comment]
Dear @t-imamichi , 
thank you very much for your kind suggestions!
I've rewritten the section to `03_minimum_eigen_optimizer` tutorial and removed it from `10_warm_start_qaoa`. Is it better like this?

Also, I understand your objection concerning the utility functions - they really are pretty easy :-)
