### ISSUE TITLE
Failure on test.algorithms.test_grover_optimizer.TestGroverOptimizer.test_samples_and_raw_samples

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-optimization#88]
### Information

- **Qiskit Optimization version**: 0.1.0 or 0.2.0
- **Python version**: >=3.6
- **Operating system**: MacOS or Ubuntu

### What is the current behavior?
The following test always fails locally on MacOS with Terra/Aer from master or pypi. On the Ubuntu CI, if I build Aer from master there, it works. If I get Aer from pypi, it fails:
```
==============================
Failed 1 tests - output below:
==============================

test.algorithms.test_grover_optimizer.TestGroverOptimizer.test_samples_and_raw_samples
--------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/home/runner/work/qiskit-optimization/qiskit-optimization/test/algorithms/test_grover_optimizer.py", line 193, in test_samples_and_raw_samples
    np.testing.assert_array_almost_equal(result.x, result.samples[0].x)

      File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1044, in assert_array_almost_equal
    precision=decimal)

      File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)

    AssertionError: 
Arrays are not almost equal to 6 decimals

Mismatched elements: 1 / 2 (50%)
Max absolute difference: 1.
Max relative difference: 1.
 x: array([0., 0.])
 y: array([1., 0.])
```

### Steps to reproduce the problem

Run test: test.algorithms.test_grover_optimizer.TestGroverOptimizer.test_samples_and_raw_samples

### What is the expected behavior?

It should work

**Comment by manoelmarques** [comment]
This issue is preventing Stable PRs from passing unit tests

**Comment by woodsp-ibm** [comment]
I added the priority label since this failure is holding up PRs in stable from being merged as they are failing this unit test there, so if this can be looked at with some urgency.

**Comment by a-matsuo** [comment]
Hi @manoelmarques , I made a PR to fix this issue.
